### ISSUE TITLE
【提案】DAOのDiscordのサーバーロールについて

### ISSUE THREAD

**Issue by frodo821** [Coffee-Stand-DAO/proposals#10]
## 概要
権限ロールと職能ロールがくっついているのはまずいので、早急に分離したい。

## 要件
職能ロールはこれまで通り手動で増やしていく感じでよいが、職能ロールに与えられた権限は一旦全て消すこと。
権限ロールについては、管理者(呼称未定、`administrator` / `admin` か `moderator` / `mod` が提案済み)とコミュニティ仲裁者 (呼称未定、`moderator` / `mod` か `community manager` が提案済み)を作る。

管理者はサーバーに対する全般的な管理権限を有し、コミュニティ仲裁者はメンバーに対する管理権限(`kick` / `ban` / `timeout` など)を有する。

## 動機
適当に振られる職能ロールに権限が付随している状態は、人数が増えてきた現状を鑑みると流石にやばい。

**Comment by hideakiimoto** [comment]
DAO Contributor（管理権限のあるロール）
Community Manager（管理権限のないロール）
を作成し、職能ロールはこれまでと同じ申請性として特別な権限は付与しない形にしてます

**Comment by hideakiimoto** [comment]
ロール作成済み
