### ISSUE TITLE
【検討】CSD定例会週1　曜日時間の決定

### ISSUE THREAD

**Issue by Nako-chan** [Coffee-Stand-DAO/proposals#14]
・進捗の共有
・新メンバーのオンボード
・貢献者の評価会

を目的に定例会を設置

●曜日と時間の決定

**Comment by ikisuke** [comment]
モデレーターと書記を分けて(コミュニケーションミスをなるべく可視化するために)、定例会スレッドにためた方がいいかもしれないですね(Githubのissueが良さそうかも？)

**Comment by frodo821** [comment]
@ikisuke discussionsつかおー
https://github.com/Coffee-Stand-DAO/proposals/discussions
