### ISSUE TITLE
CSDのLP制作

### ISSUE THREAD

**Issue by Nako-chan** [Coffee-Stand-DAO/proposals#5]
y.higashimori　さんがLP制作いただける？
https://discord.com/channels/977834949971415060/977915893076066334/983715214971269161

**Comment by hideakiimoto** [comment]
一旦imotoが作る

**Comment by hideakiimoto** [comment]
ひとまず作ってみました！

https://csdao.carrd.co/

**Comment by hideakiimoto** [comment]
モバイルへの対応がまだだがLP作成完了
https://csdao.cc/
