### ISSUE TITLE
ウォレットどうする問題

### ISSUE THREAD

**Issue by Nako-chan** [Coffee-Stand-DAO/proposals#9]

**Comment by Nako-chan** [comment]
・グノーシスセーフ使うか

どうする？

**Comment by Nako-chan** [comment]
メンバー選定　（すし）

**Comment by hideakiimoto** [comment]
誰を承認者にするか。
現状はアサインしたメンバーにお願いしたいと思います
@frodo821 @Akira-Taniguchi @ikisuke @Nako-chan

**Comment by ikisuke** [comment]
matic:0x46C1FAE272AF3D2659e32A9669b82E1B6b58F9eA
にてマルチシグウォレットを作成しております

**Comment by Nako-chan** [comment]
@ikisuke これって招待済みですか？
コネクトしたけど、ウォレットが表示されなかった

**Comment by ikisuke** [comment]
@Nako-chan 招待済みです
https://gnosis-safe.io/app/matic:0x46C1FAE272AF3D2659e32A9669b82E1B6b58F9eA/home
をご確認いただければと

**Comment by ikisuke** [comment]
一旦、メンバーをsafeに招待したのでこちらのissueをクローズします
